site_name: TurboNAS

# Repository
repo_name: TurboNAS
repo_url: https://github.com/louisonsarlinmagnus/TurboNAS

nav:
  - Accueil: index.md
  - Installation d'Ubuntu: ubuntu_install.md
  - Communication SSH: comm_ssh.md
  - Docker: docker.md
  - Services:
    - Nextcloud: nextcloud.md
    - Plex: plex.md
    - Minecraft: minecraft.md
  - Archives:
    - Multipass: multipass.md
    - Cloud-init: cloud-init.md

theme: 
  name: material
  highlightjs: true

markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - footnotes

extra_css:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js

copyright: '&copy; 2021 Louison SARLIN--MAGNUS'
